meterdata <- read.table(paste(getwd(),"/household_power_consumption.txt",sep=""), sep =";", header= TRUE)
filtereddata <- subset(meterdata, Date == '1/2/2007' | Date == '2/2/2007')
filtereddata$DateTime <- strptime(paste(filtereddata$Date, filtereddata$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
png(file="plot3.png", width = 480, height = 480, units = "px", pointsize = 12)
plot(filtereddata$DateTime,as.numeric(paste(filtereddata$Sub_metering_1)),ylim=range(c(as.numeric(paste(filtereddata$Sub_metering_1)),filtereddata$Sub_metering_2,filtereddata$Sub_metering_3)),type="l",xlab="",ylab="Energy Sub metering")
par(new=TRUE)
plot(filtereddata$DateTime,as.numeric(paste(filtereddata$Sub_metering_2)),ylim=range(c(as.numeric(paste(filtereddata$Sub_metering_1)),as.numeric(paste(filtereddata$Sub_metering_2)),filtereddata$Sub_metering_3)),type="l",col="red",xlab="",ylab="")
par(new=TRUE)
plot(filtereddata$DateTime,filtereddata$Sub_metering_3,ylim=range(c(as.numeric(paste(filtereddata$Sub_metering_1)),as.numeric(paste(filtereddata$Sub_metering_2)),filtereddata$Sub_metering_3)),type="l",col="blue",xlab="",ylab="")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black",rep("red",1),rep("blue",1)), lwd =c(1.5,1.5,1.5))
dev.off()
